export interface DigestItem { league: string; home: string; away: string; kickoffUtc: string; probs: [number, number, number]; score: string }
export const esc = (s: string) => s.replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] as string));
const pct = (x: number) => `${Math.round(x * 100)}%`, hhmm = (iso: string) => new Date(iso).toISOString().slice(11, 16) + " UTC";
/** The match day email. Predictions are probabilities, and the footer says so. */
export function buildDigest(items: DigestItem[], date: string, unsubUrl: string, siteUrl: string) {
  const subject = `GoalGrid match day: ${items.length} prediction${items.length === 1 ? "" : "s"} for ${date}`, note = "Predictions are probabilities, not guarantees, and can be wrong. Please follow the rules where you live.";
  const rows = items.map(i => `<tr><td style="padding:12px 0;border-bottom:1px solid #e4e9ee"><div style="font-size:12px;color:#5b6b78">${esc(i.league)}, ${hhmm(i.kickoffUtc)}</div><div style="font-weight:700;font-size:16px;margin:2px 0">${esc(i.home)} vs ${esc(i.away)}</div><div style="font-size:14px;color:#26323d">Home ${pct(i.probs[0])} &middot; Draw ${pct(i.probs[1])} &middot; Away ${pct(i.probs[2])} &middot; Likely score ${esc(i.score)}</div></td></tr>`).join("");
  const html = `<!doctype html><html><body style="margin:0;background:#f4f7f9;font-family:Arial,Helvetica,sans-serif"><div style="max-width:560px;margin:0 auto;padding:24px"><div style="font-size:22px;font-weight:800;color:#0b1420">Goal<span style="color:#00b85c">Grid</span></div><h1 style="font-size:20px;color:#0b1420;margin:16px 0 4px">Today's top predictions</h1><table role="presentation" width="100%" style="border-collapse:collapse">${rows}</table><p style="margin:20px 0"><a href="${esc(siteUrl)}/dashboard" style="background:#00e676;color:#04210f;text-decoration:none;font-weight:700;padding:12px 20px;border-radius:10px;display:inline-block">Open the dashboard</a></p><p style="font-size:12px;color:#5b6b78">${note}</p><p style="font-size:12px;color:#5b6b78"><a href="${esc(unsubUrl)}" style="color:#5b6b78">Unsubscribe</a></p></div></body></html>`;
  const text = `GoalGrid match day, ${date}\n\n${items.map(i => `${i.league}, ${hhmm(i.kickoffUtc)}\n${i.home} vs ${i.away}\nHome ${pct(i.probs[0])}, Draw ${pct(i.probs[1])}, Away ${pct(i.probs[2])}, likely score ${i.score}`).join("\n\n")}\n\n${siteUrl}/dashboard\n\n${note}\nUnsubscribe: ${unsubUrl}\n`;
  return { subject, html, text };
}
