"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
const L=[['premier-league','Premier League'],['la-liga','La Liga'],['serie-a','Serie A'],['bundesliga','Bundesliga'],['ligue-1','Ligue 1']] as const;
interface BacktestModel{id:string;name:string;matches:number;logLoss:number|null;brier1x2:number|null;ece:number|null;coverage:number;failureRate:number}
interface BacktestResult{folds?:unknown[];baseline?:{logLoss?:number};models?:BacktestModel[]}
interface BacktestRun{id:string;created_at:string;league_slug:string;folds:number;model_ids?:string[]}
interface ControlModel{model_id:string;name:string;status:string}
export interface AdminModelOption { id: string; name: string; family: string; status: string }
export function AdminBacktestPanel({ initialModels }: { initialModels: AdminModelOption[] }) {
 const [league,setLeague]=useState('premier-league'),[models,setModels]=useState(initialModels),[selected,setSelected]=useState(initialModels.filter(x=>x.status==='production').slice(0,15).map(x=>x.id)),[folds,setFolds]=useState(4),[result,setResult]=useState<BacktestResult|null>(null),[runs,setRuns]=useState<BacktestRun[]>([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/admin/backtests');const j=await r.json().catch(()=>({}));if(r.ok)setRuns(j.runs||[])}
 useEffect(()=>{let off=false;fetch('/api/admin/backtests').then(async r=>({ok:r.ok,j:await r.json().catch(()=>({}))})).then(({ok,j})=>{if(!off&&ok)setRuns(j.runs||[])});return()=>{off=true}},[]);
 async function changeLeague(next:string){setLeague(next);const r=await fetch('/api/admin/control-plane');const j=await r.json().catch(()=>({}));if(r.ok&&Array.isArray(j.models)){const a=(j.models as ControlModel[]).filter(x=>x.status!=='retired').map(x=>({id:x.model_id,name:x.name,family:'',status:x.status}));setModels(a);setSelected(a.filter((x:AdminModelOption)=>x.status==='production').slice(0,15).map((x:AdminModelOption)=>x.id));}}
 function toggle(id:string){setSelected(a=>a.includes(id)?a.filter(x=>x!==id):a.length<30?[...a,id]:a)}
 async function run(){setBusy(true);setMsg('');setResult(null);try{const r=await fetch('/api/admin/backtests',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({league,folds,startFraction:0.5,modelIds:selected})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Backtest failed');setResult(j.result);await load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}}
 return <><div className="row"><div><h1>Backtesting</h1><p className="sub">Admin research only. Walk-forward evaluation uses time-ordered real football history and stores an immutable result record.</p></div><Link className="btn sm" href="/admin">Operations</Link></div>
 <div className="card" style={{display:'grid',gap:14,marginTop:16}}><div className="grid"><label>League<select value={league} onChange={e=>void changeLeague(e.target.value)}>{L.map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></label><label>Folds<select value={folds} onChange={e=>setFolds(Number(e.target.value))}>{[2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></label></div><div><b>Models · {selected.length}/30</b><div className="chips" style={{marginTop:8}}>{models.map(m=><button key={m.id} type="button" className={`chip ${selected.includes(m.id)?'on':''}`} onClick={()=>toggle(m.id)}>{m.name}</button>)}</div></div><button className="btn p" disabled={busy||selected.length<3} onClick={()=>void run()}>{busy?'Running walk-forward backtest…':'Run backtest'}</button>{msg&&<div className="err">{msg}</div>}</div>
 {result&&<div className="card scroll" style={{marginTop:16}}><h2>Latest result</h2><div className="meta"><span>{result.folds?.length??0} folds</span><span>Baseline log loss {Number(result.baseline?.logLoss).toFixed(4)}</span></div><table><thead><tr><th>MODEL</th><th>MATCHES</th><th>LOG LOSS</th><th>BRIER</th><th>ECE</th><th>COVERAGE</th><th>FAIL RATE</th></tr></thead><tbody>{(result.models||[]).map(m=><tr key={m.id}><td>{m.name}</td><td>{m.matches}</td><td>{m.logLoss==null?'—':Number(m.logLoss).toFixed(4)}</td><td>{m.brier1x2==null?'—':Number(m.brier1x2).toFixed(4)}</td><td>{m.ece==null?'—':Number(m.ece).toFixed(4)}</td><td>{(Number(m.coverage)*100).toFixed(1)}%</td><td>{(Number(m.failureRate)*100).toFixed(1)}%</td></tr>)}</tbody></table></div>}
 <h2>Stored backtests</h2><div className="card scroll">{runs.length?<table><thead><tr><th>WHEN</th><th>LEAGUE</th><th>FOLDS</th><th>MODELS</th></tr></thead><tbody>{runs.map(r=><tr key={r.id}><td>{new Date(r.created_at).toUTCString()}</td><td>{r.league_slug}</td><td>{r.folds}</td><td>{r.model_ids?.length??0}</td></tr>)}</tbody></table>:<p className="note">No backtests stored yet.</p>}</div></>;
}
