"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
const L=[['premier-league','Premier League'],['la-liga','La Liga'],['serie-a','Serie A'],['bundesliga','Bundesliga'],['ligue-1','Ligue 1']] as const;
interface CompareRow{id:string;name:string;family:string;weight:number;home:number;draw:number;away:number;xgHome:number|null;xgAway:number|null}
interface Spread{home:number;draw:number;away:number}
export default function ModelCompare(){
 const [league,setLeague]=useState('premier-league'),[teams,setTeams]=useState<string[]>([]),[home,setHome]=useState(''),[away,setAway]=useState(''),[rows,setRows]=useState<CompareRow[]>([]),[spread,setSpread]=useState<Spread|null>(null),[msg,setMsg]=useState('');
 useEffect(()=>{fetch(`/api/simulation/teams?league=${league}`).then(r=>r.json()).then(j=>{const t=j.teams||[];setTeams(t);setHome(t[0]||'');setAway(t[1]||'')}).catch(()=>setMsg('Teams unavailable.'))},[league]);
 async function run(){if(!home||!away||home===away)return;setMsg('');const r=await fetch(`/api/simulation/compare?league=${league}&home=${encodeURIComponent(home)}&away=${encodeURIComponent(away)}`);const j=await r.json().catch(()=>({}));if(!r.ok){setMsg(j.error||'Comparison failed.');return;}setRows(j.models||[]);setSpread(j.spread||null);}
 return <><div className="row"><div><h1>Model Comparison</h1><p className="sub">Premium research view. Every value comes from the stored GoalGrid model ensemble for the selected matchup.</p></div><Link className="btn sm" href="/simulation">Back to Simulation</Link></div><div className="card" style={{display:'grid',gap:12,marginTop:16}}><div className="grid"><label>League<select value={league} onChange={e=>{setLeague(e.target.value);setRows([]);setMsg('')}}>{L.map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></label><label>Home<select value={home} onChange={e=>setHome(e.target.value)}>{teams.map(t=><option key={t}>{t}</option>)}</select></label><label>Away<select value={away} onChange={e=>setAway(e.target.value)}>{teams.map(t=><option key={t}>{t}</option>)}</select></label></div><button className="btn p" onClick={()=>void run()} disabled={!home||!away||home===away}>Compare models</button>{msg&&<div className="err">{msg}</div>}</div>{rows.length>0&&<><div className="card scroll"><table><thead><tr><th>MODEL</th><th>WEIGHT</th><th>HOME</th><th>DRAW</th><th>AWAY</th><th>xG H</th><th>xG A</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.name}<div className="note">{x.family}</div></td><td>{(x.weight*100).toFixed(1)}%</td><td>{(x.home*100).toFixed(1)}%</td><td>{(x.draw*100).toFixed(1)}%</td><td>{(x.away*100).toFixed(1)}%</td><td>{x.xgHome==null?'—':Number(x.xgHome).toFixed(2)}</td><td>{x.xgAway==null?'—':Number(x.xgAway).toFixed(2)}</td></tr>)}</tbody></table></div><div className="card"><h2>Model disagreement</h2><div className="pl"><div><b>{spread? (spread.home*100).toFixed(1)+' pp':''}</b>Home spread</div><div><b>{spread? (spread.draw*100).toFixed(1)+' pp':''}</b>Draw spread</div><div><b>{spread? (spread.away*100).toFixed(1)+' pp':''}</b>Away spread</div></div><p className="note" style={{marginTop:10}}>Wide spread means the models disagree; it is not evidence that one model is wrong.</p></div></>}</>;
}
