import { NextResponse } from "next/server";
import { z } from "zod";
import { requireMember, fail } from "@/lib/community/api";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { createNotification } from "@/lib/notifications/server";
import { LIMIT_MESSAGE, allow } from "@/lib/security/limits";
const idSchema=z.string().uuid();
export async function POST(req:Request,ctx:{params:Promise<{id:string}>}){const me=await requireMember();if(me instanceof NextResponse)return me;if(!(await allow(me.id,"circle")))return fail(LIMIT_MESSAGE,429);const id=(await ctx.params).id;if(!idSchema.safeParse(id).success)return fail("Invalid circle.",400);const action=z.object({action:z.enum(["join","leave","add"]),username:z.string().regex(/^[a-z0-9_]{3,20}$/).optional()}).safeParse(await req.json().catch(()=>null));if(!action.success)return fail("Invalid action.",400);const db=supabaseAdmin(),{data:c}=await db.from("private_circles").select("id,owner_id").eq("id",id).maybeSingle();if(!c)return fail("Circle not found.",404);const {data:mem}=await db.from("private_circle_members").select("role").eq("circle_id",id).eq("user_id",me.id).maybeSingle();if(action.data.action==="join"){if(!mem)await db.from("private_circle_members").insert({circle_id:id,user_id:me.id,role:"member"});return NextResponse.json({joined:true});}if(action.data.action==="leave"){if(c.owner_id===me.id)return fail("The owner cannot leave the circle.",400);await db.from("private_circle_members").delete().eq("circle_id",id).eq("user_id",me.id);return NextResponse.json({joined:false});}if(c.owner_id!==me.id||!action.data.username)return fail("Only the owner can add members by username.",403);const {data:p}=await db.from("profiles").select("id").eq("username",action.data.username).maybeSingle();if(!p)return fail("User not found.",404);await db.from("private_circle_members").upsert({circle_id:id,user_id:p.id,role:"member"},{onConflict:"circle_id,user_id"});
await createNotification({userId:p.id,type:"community",title:"Added to private circle",body:`You were added to a private GoalGrid discussion circle.`,href:`/community/circles/${id}`,dedupeKey:`circle:add:${id}:${p.id}`});
return NextResponse.json({added:true});}
